=== cnoelle/ogema-launcher/src/ogema-launcher/src/main/resources/org/ogema/launcher/config-1.2.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ogema="http://www.ogema-source.net/config"
	targetNamespace="http://www.ogema-source.net/config"
	elementFormDefault="qualified">
	<element name="configuration">
		<complexType>
			<all>
				<element name="frameworkbundle" type="ogema:bundle"
					minOccurs="0" maxOccurs="1" />

				<element name="bundles" minOccurs="1" maxOccurs="1">
					<complexType>
						<sequence>
							<annotation>
								<documentation>
									NOTE: Either
									<b>file</b>
									OR
									<b>groupId, artifactId and version</b>
									is required!
								</documentation>
							</annotation>
							<element name="bundle" type="ogema:bundle" minOccurs="1"
								maxOccurs="unbounded" />
						</sequence>
					</complexType>
				</element>

				<element name="properties" minOccurs="0">
					<complexType>
						<sequence>
							<element name="property" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<attribute name="key" type="string" use="required" />
									<attribute name="value" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

				<element name="deleteList" minOccurs="0">
					<complexType>
						<sequence>
							<annotation>
								<documentation>
									A simple list of files / directories that should be deleted upon a clean
									start of the OGEMA.
								</documentation>
							</annotation>
							<element name="file" type="string" minOccurs="1"
								maxOccurs="unbounded" />
						</sequence>
					</complexType>
				</element>
			</all>
		</complexType>
	</element>

	<simpleType name="binDir">
		<restriction base="string">
			<pattern
				value="(([\w\.]+(-|_)?)+(/|\\)?([\w\.]+(-|_)?)+|([\w\.]+(-|_)?)+)+"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="fileName">
		<restriction base="string">
			<pattern value="[\w\-_\.]+.jar"></pattern>
		</restriction>
	</simpleType>

	<complexType name="bundle">
		<attribute name="dir" type="ogema:binDir" default="bin">
			<annotation>
				<documentation>
					Relative directory location to the bundle.
					If the
					bundle couldn't be resolved via maven
					then this location will be
					checked. Additionally
					this location is used during the build phase
					and
					the bundle will be copied into this directory.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="start" type="boolean" default="true" />
		<attribute name="startLevel" type="integer" default="4" />
		<attribute name="groupId" type="string">
			<annotation>
				<documentation>
					Group ID of the maven artifact. Must not contain
					colon(s) (":").
				</documentation>
			</annotation>
		</attribute>
		<attribute name="artifactId" type="string">
			<annotation>
				<documentation>
					Artifact ID of the maven artifact. Must not contain
					colon(s) (":").
				</documentation>
			</annotation>
		</attribute>
		<attribute name="version" type="string">
			<annotation>
				<documentation>
					Version of the maven artifact. Must not contain
					colon(s) (":").
				</documentation>
			</annotation>
		</attribute>
		<attribute name="file" type="ogema:fileName">
			<annotation>
				<documentation>
					This attribute contains the file name. It has to end
					with ".jar" and must not contain any directory
					structures.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

</schema>

=== cnoelle/ogema-launcher/src/ogema-launcher/example/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration 
[
	<!ENTITY slf4j-version "1.7.25">
	<!ENTITY logback-version "1.2.3">
]>
<configuration xmlns="http://www.ogema-source.net/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ogema-source.net/config https://www.ogema-source.net/config-1.2.1.xsd">
  	<!-- Start the Felix OSGi framework -->
	<frameworkbundle dir="bin/system" groupId="org.apache.felix" artifactId="org.apache.felix.framework" version="5.6.8" />
	<!-- Alternatively, we could start the Equinox or Knopflerfish OSGi framework bundles -->
    <!--<frameworkbundle dir="bin/system" groupId="org.eclipse.tycho" artifactId="org.eclipse.osgi" version="3.12.0.v20170512-1932" /> -->
    <!--<frameworkbundle dir="bin/system" groupId="de.cnoelle.external" artifactId="org.knopflerfish.framework" version="8.0.4.v2" />-->
	
	<bundles>
		<!-- OSGi bundles -->
		<bundle dir="bin/system" groupId="org.apache.felix" artifactId="org.apache.felix.framework.security" version="2.6.0" startLevel="1" />
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.scr" version="2.0.12" startLevel="2" />
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.configadmin" version="1.8.14" startLevel="2" />
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.metatype" version="1.1.2" startLevel="2" />
		<bundle dir="bin/osgi" groupId="org.osgi" artifactId="org.knopflerfish.bundle.useradmin" version="4.1.1" startLevel="2" />
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.eventadmin" version="1.4.8" startLevel="2" />
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.gogo.runtime" version="1.0.6" startLevel="2" /> <!-- 0.16.2 or 1.0.6 -->
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.gogo.command" version="1.0.2" startLevel="2" /><!-- 0.16.0 or 1.0.2 -->
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.gogo.shell" version="1.0.0" startLevel="2" /><!-- 0.12.0 or 1.0.0 -->
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.shell.remote" version="1.2.0" startLevel="2" /><!-- 1.1.2 or 1.2.0 -->
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.fileinstall" version="3.6.0" startLevel="1" />
		
		<!-- Jetty servlet container -->
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.http.servlet-api" version="1.1.2" startLevel="2" />
		<bundle dir="bin/osgi" groupId="org.apache.felix" artifactId="org.apache.felix.http.jetty" version="3.1.6" startLevel="2" /> <!-- version 3.2.0 does not work with PKCS12 keystore format -->
		<bundle dir="bin/osgi" groupId="org.eclipse.jetty" artifactId="jetty-servlets" version="9.2.14.v20151106" />

		<!-- logging bundles -->			
		<bundle dir="bin/logging" groupId="org.slf4j" artifactId="slf4j-api" version="&slf4j-version;" />
		<bundle dir="bin/logging" groupId="ch.qos.logback" artifactId="logback-classic" version="&logback-version;" />
		<bundle dir="bin/logging" groupId="ch.qos.logback" artifactId="logback-core" version="&logback-version;" /> 

		<!-- felix web console -->
		<bundle dir="bin/felix-webconsole" groupId="org.apache.felix" artifactId="org.apache.felix.webconsole" version="4.3.4" />
		<bundle dir="bin/felix-webconsole" groupId="commons-fileupload" artifactId="commons-fileupload" version="1.3.3" />
		<bundle dir="bin/felix-webconsole" groupId="commons-io" artifactId="commons-io" version="2.5" />
		<bundle dir="bin/felix-webconsole" groupId="commons-codec" artifactId="commons-codec" version="1.10" />
		<bundle dir="bin/felix-webconsole" groupId="org.apache.felix" artifactId="org.apache.felix.webconsole.plugins.event" version="1.1.6" />
		<bundle dir="bin/felix-webconsole" groupId="org.apache.felix" artifactId="org.apache.felix.inventory" version="1.0.4" />
		<bundle dir="bin/felix-webconsole" groupId="org.apache.felix" artifactId="org.apache.felix.webconsole.plugins.ds" version="2.0.2" />
		<bundle dir="bin/felix-webconsole" groupId="org.apache.felix" artifactId="org.apache.felix.webconsole.plugins.obr" version="1.0.2" />
		<bundle dir="bin/felix-webconsole" groupId="org.apache.felix" artifactId="org.apache.felix.webconsole.plugins.memoryusage" version="1.0.6" />
		<bundle dir="bin/felix-webconsole" groupId="org.json" artifactId="json" version="20170516" />  

		<bundle dir="bin/osgi" groupId="org.ops4j.pax.url" artifactId="pax-url-aether" version="2.5.2" startLevel="1" />
		<!-- groovy: needs package sun.reflect in org.osgi.framework.system.packages.extra -->
		<bundle dir="bin/tools" groupId="org.codehaus.groovy" artifactId="groovy-all" version="2.4.12" />
		
	</bundles>

	<properties>
	
		<property key="org.osgi.framework.system.packages.extra" value="sun.reflect,sun.misc"/>
		<property key="org.osgi.framework.bsnversion" value="multiple" />
		<property key="osgi.shell.telnet.port" value="64362" />

		<property key="eclipse.ignoreApp" value="true" />
		<property key="osgi.console" value="" />
		<property key="felix.log.level" value="info" />
		<property key="ds.showtrace" value="false" />

		<property key="org.osgi.service.http.port" value="8080" />
		<property key="org.osgi.service.http.port.secure" value="8443" />
		<property key="org.osgi.service.http.secure.enabled" value="true" />

		<property key="org.apache.felix.http.debug" value="false" />
		<property key="org.apache.felix.https.enable" value="true" />
		<property key="org.apache.felix.https.keystore" value="config/keystore" />
	 	<property key="org.apache.felix.https.keystore.password" value="testtest" />
		<property key="org.apache.felix.https.keystore.key.password" value="testtest" />

		<property key="felix.fileinstall.log.level" value="-1" />
	</properties>

	<!-- List of files and directories to delete in case of a clean start -->
	<deleteList>
		<file>data/osgi-storage</file>
	</deleteList>
</configuration>
